import { TypeTestProvider } from './context/TypeTestContext'
import ToasterContext from './context/ToasterContext'
import AuthContext from './context/AuthContext'
import Navbar from './components/Navbar'

import './styles/global.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Typing Test',
  description: 'Generated by create next app',
}
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className='dark'>
      <body className={`dark:bg-blue-600 ${inter.className}`}>
        <AuthContext>
          <TypeTestProvider>
            <ToasterContext />
              <Navbar />
              {children}
          </TypeTestProvider>
        </AuthContext>
      </body>
    </html>
  )
}
